### ISSUE TITLE
TypeError: Return value of Tidycode\MetaRobotsTag\Model\SetMetaRobots::attributeIsFlaggedInEntity() must be of the type bool, 

### ISSUE THREAD

**Issue by LotsofPixels** [TidycodeIT/magento2-meta-robots#2]
This is a M2.4.*  and I am getting the following random error:
TypeError: Return value of Tidycode\MetaRobotsTag\Model\SetMetaRobots::attributeIsFlaggedInEntity() must be of the type bool, 
null returned in /data/web/application/vendor/tidycode/meta-robots-tag/Model/SetMetaRobots.php:54 Stack trace:

Is there a way to avoid that?

**Comment by LotsofPixels** [comment]
I have modified Tidycode\MetaRobotsTag\Model\SetMetaRobots::attributeIsFlaggedInEntity() 
`--- Unsaved view (15)
+++ Unsaved view (16)
@@ -51,7 +51,9 @@
      */
     protected function attributeIsFlaggedInEntity(DataObject $entity, $attributeCode): bool
     {
-        return $entity->getData($attributeCode);
+        $attributeCodeValue = $entity->getData($attributeCode);
+        is_null($attributeCodeValue ) ? $attributeCodeValue = "0" : $attributeCodeValue = $entity->getData($attributeCode);
+        return $attributeCodeValue;
     }
 
     /**
@@ -63,4 +65,5 @@
     {
         return array_search(strtolower($needle), array_map('strtolower', $haystack));
     }
-}
\ No newline at end of file
+}
+`

**Comment by jBjerkli** [comment]
Does this work as of October, 2023 or Magento 2.4.3?
We have installed it, and the three new options have appeared under SEO section on the product page. However, even after enabling each option, the head section still insists on <meta name="robots" content="INDEX,FOLLOW"/>

**Comment by deveddie** [comment]
> I have modified Tidycode\MetaRobotsTag\Model\SetMetaRobots::attributeIsFlaggedInEntity()
> 
> ` protected function attributeIsFlaggedInEntity(DataObject $entity, $attributeCode): bool { $attributeCodeValue = $entity->getData($attributeCode); is_null($attributeCodeValue ) ? $attributeCodeValue = "0" : $attributeCodeValue = $entity->getData($attributeCode); return $attributeCodeValue; }`

Hi, thanks for the fix! Needs committing... ;)

**Comment by deveddie** [comment]
> I have modified Tidycode\MetaRobotsTag\Model\SetMetaRobots::attributeIsFlaggedInEntity()
> 
> ` protected function attributeIsFlaggedInEntity(DataObject $entity, $attributeCode): bool { $attributeCodeValue = $entity->getData($attributeCode); is_null($attributeCodeValue ) ? $attributeCodeValue = "0" : $attributeCodeValue = $entity->getData($attributeCode); return $attributeCodeValue; }`

Thanks for this fix!
